### ISSUE TITLE
DMAWriter typo?

### ISSUE THREAD

**Issue by ret** [enjoy-digital/netv2#7]
Should https://github.com/enjoy-digital/netv2/blob/57227db549ba58b146fcc869cc8ba1297d330e6d/netv2.py#L236 refer to DMAWriter instead of Reader?  Looks like it might have been a cut/paste oversight in the originating change (https://github.com/enjoy-digital/netv2/commit/72082ce7882624eec6028265fb09664165ed1d72).

**Comment by enjoy-digital** [comment]
Thanks @ret for the feedback. This has been fixed with https://github.com/enjoy-digital/netv2/commit/0a4ea0263ac2a87627d6bcb5aa8b111e7aa09ff1. This project was an experiment and is no longer maintained, so if you want an up to date design with the NeTV2, I would recommend looking at the NeTV2 support in LiteX-Boards: https://github.com/litex-hub/litex-boards/blob/master/litex_boards/targets/netv2.py.
